/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Module2RouteImport } from './routes/module2'
import { Route as CoolModuleRouteImport } from './routes/cool-module'
import { Route as IndexRouteImport } from './routes/index'

const Module2Route = Module2RouteImport.update({
  id: '/module2',
  path: '/module2',
  getParentRoute: () => rootRouteImport,
} as any)
const CoolModuleRoute = CoolModuleRouteImport.update({
  id: '/cool-module',
  path: '/cool-module',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cool-module': typeof CoolModuleRoute
  '/module2': typeof Module2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cool-module': typeof CoolModuleRoute
  '/module2': typeof Module2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cool-module': typeof CoolModuleRoute
  '/module2': typeof Module2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cool-module' | '/module2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cool-module' | '/module2'
  id: '__root__' | '/' | '/cool-module' | '/module2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoolModuleRoute: typeof CoolModuleRoute
  Module2Route: typeof Module2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/module2': {
      id: '/module2'
      path: '/module2'
      fullPath: '/module2'
      preLoaderRoute: typeof Module2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cool-module': {
      id: '/cool-module'
      path: '/cool-module'
      fullPath: '/cool-module'
      preLoaderRoute: typeof CoolModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoolModuleRoute: CoolModuleRoute,
  Module2Route: Module2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
